uni= set()

num1=int(input("Enter The Number  : "))
uni.add(num1)
num2=int(input("Enter The Number  : "))
uni.add(num2)
num3=int(input("Enter The Number  : "))
uni.add(num3)
num4=int(input("Enter The Number  : "))
uni.add(num4)
num5=int(input("Enter The Number  : "))
uni.add(num5)
num6=int(input("Enter The Number  : "))
uni.add(num6)
num7=int(input("Enter The Number  : "))
uni.add(num7)
num8=int(input("Enter The Number  : "))
uni.add(num8)

print(uni)